// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: posting_message.proto

#ifndef PROTOBUF_posting_5fmessage_2eproto__INCLUDED
#define PROTOBUF_posting_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_posting_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsdoc_infoImpl();
void InitDefaultsdoc_info();
void InitDefaultsPostingImpl();
void InitDefaultsPosting();
void InitDefaultsPostingListImpl();
void InitDefaultsPostingList();
inline void InitDefaults() {
  InitDefaultsdoc_info();
  InitDefaultsPosting();
  InitDefaultsPostingList();
}
}  // namespace protobuf_posting_5fmessage_2eproto
namespace posting_message {
class Posting;
class PostingDefaultTypeInternal;
extern PostingDefaultTypeInternal _Posting_default_instance_;
class PostingList;
class PostingListDefaultTypeInternal;
extern PostingListDefaultTypeInternal _PostingList_default_instance_;
class doc_info;
class doc_infoDefaultTypeInternal;
extern doc_infoDefaultTypeInternal _doc_info_default_instance_;
}  // namespace posting_message
namespace posting_message {

// ===================================================================

class doc_info : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:posting_message.doc_info) */ {
 public:
  doc_info();
  virtual ~doc_info();

  doc_info(const doc_info& from);

  inline doc_info& operator=(const doc_info& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  doc_info(doc_info&& from) noexcept
    : doc_info() {
    *this = ::std::move(from);
  }

  inline doc_info& operator=(doc_info&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const doc_info& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const doc_info* internal_default_instance() {
    return reinterpret_cast<const doc_info*>(
               &_doc_info_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(doc_info* other);
  friend void swap(doc_info& a, doc_info& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline doc_info* New() const PROTOBUF_FINAL { return New(NULL); }

  doc_info* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const doc_info& from);
  void MergeFrom(const doc_info& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(doc_info* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 positions = 3;
  int positions_size() const;
  void clear_positions();
  static const int kPositionsFieldNumber = 3;
  ::google::protobuf::int32 positions(int index) const;
  void set_positions(int index, ::google::protobuf::int32 value);
  void add_positions(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      positions() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_positions();

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 term_frequency = 2;
  void clear_term_frequency();
  static const int kTermFrequencyFieldNumber = 2;
  ::google::protobuf::int32 term_frequency() const;
  void set_term_frequency(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:posting_message.doc_info)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > positions_;
  mutable int _positions_cached_byte_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 term_frequency_;
  mutable int _cached_size_;
  friend struct ::protobuf_posting_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_posting_5fmessage_2eproto::InitDefaultsdoc_infoImpl();
};
// -------------------------------------------------------------------

class Posting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:posting_message.Posting) */ {
 public:
  Posting();
  virtual ~Posting();

  Posting(const Posting& from);

  inline Posting& operator=(const Posting& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Posting(Posting&& from) noexcept
    : Posting() {
    *this = ::std::move(from);
  }

  inline Posting& operator=(Posting&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Posting& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Posting* internal_default_instance() {
    return reinterpret_cast<const Posting*>(
               &_Posting_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Posting* other);
  friend void swap(Posting& a, Posting& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Posting* New() const PROTOBUF_FINAL { return New(NULL); }

  Posting* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Posting& from);
  void MergeFrom(const Posting& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Posting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 positions = 3;
  int positions_size() const;
  void clear_positions();
  static const int kPositionsFieldNumber = 3;
  ::google::protobuf::int32 positions(int index) const;
  void set_positions(int index, ::google::protobuf::int32 value);
  void add_positions(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      positions() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_positions();

  // int32 docID = 1;
  void clear_docid();
  static const int kDocIDFieldNumber = 1;
  ::google::protobuf::int32 docid() const;
  void set_docid(::google::protobuf::int32 value);

  // int32 term_frequency = 2;
  void clear_term_frequency();
  static const int kTermFrequencyFieldNumber = 2;
  ::google::protobuf::int32 term_frequency() const;
  void set_term_frequency(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:posting_message.Posting)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > positions_;
  mutable int _positions_cached_byte_size_;
  ::google::protobuf::int32 docid_;
  ::google::protobuf::int32 term_frequency_;
  mutable int _cached_size_;
  friend struct ::protobuf_posting_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_posting_5fmessage_2eproto::InitDefaultsPostingImpl();
};
// -------------------------------------------------------------------

class PostingList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:posting_message.PostingList) */ {
 public:
  PostingList();
  virtual ~PostingList();

  PostingList(const PostingList& from);

  inline PostingList& operator=(const PostingList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PostingList(PostingList&& from) noexcept
    : PostingList() {
    *this = ::std::move(from);
  }

  inline PostingList& operator=(PostingList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PostingList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PostingList* internal_default_instance() {
    return reinterpret_cast<const PostingList*>(
               &_PostingList_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PostingList* other);
  friend void swap(PostingList& a, PostingList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PostingList* New() const PROTOBUF_FINAL { return New(NULL); }

  PostingList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PostingList& from);
  void MergeFrom(const PostingList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PostingList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .posting_message.Posting postings = 2;
  int postings_size() const;
  void clear_postings();
  static const int kPostingsFieldNumber = 2;
  const ::posting_message::Posting& postings(int index) const;
  ::posting_message::Posting* mutable_postings(int index);
  ::posting_message::Posting* add_postings();
  ::google::protobuf::RepeatedPtrField< ::posting_message::Posting >*
      mutable_postings();
  const ::google::protobuf::RepeatedPtrField< ::posting_message::Posting >&
      postings() const;

  // int32 num_postings = 1;
  void clear_num_postings();
  static const int kNumPostingsFieldNumber = 1;
  ::google::protobuf::int32 num_postings() const;
  void set_num_postings(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:posting_message.PostingList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::posting_message::Posting > postings_;
  ::google::protobuf::int32 num_postings_;
  mutable int _cached_size_;
  friend struct ::protobuf_posting_5fmessage_2eproto::TableStruct;
  friend void ::protobuf_posting_5fmessage_2eproto::InitDefaultsPostingListImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// doc_info

// int32 id = 1;
inline void doc_info::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 doc_info::id() const {
  // @@protoc_insertion_point(field_get:posting_message.doc_info.id)
  return id_;
}
inline void doc_info::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:posting_message.doc_info.id)
}

// int32 term_frequency = 2;
inline void doc_info::clear_term_frequency() {
  term_frequency_ = 0;
}
inline ::google::protobuf::int32 doc_info::term_frequency() const {
  // @@protoc_insertion_point(field_get:posting_message.doc_info.term_frequency)
  return term_frequency_;
}
inline void doc_info::set_term_frequency(::google::protobuf::int32 value) {
  
  term_frequency_ = value;
  // @@protoc_insertion_point(field_set:posting_message.doc_info.term_frequency)
}

// repeated int32 positions = 3;
inline int doc_info::positions_size() const {
  return positions_.size();
}
inline void doc_info::clear_positions() {
  positions_.Clear();
}
inline ::google::protobuf::int32 doc_info::positions(int index) const {
  // @@protoc_insertion_point(field_get:posting_message.doc_info.positions)
  return positions_.Get(index);
}
inline void doc_info::set_positions(int index, ::google::protobuf::int32 value) {
  positions_.Set(index, value);
  // @@protoc_insertion_point(field_set:posting_message.doc_info.positions)
}
inline void doc_info::add_positions(::google::protobuf::int32 value) {
  positions_.Add(value);
  // @@protoc_insertion_point(field_add:posting_message.doc_info.positions)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
doc_info::positions() const {
  // @@protoc_insertion_point(field_list:posting_message.doc_info.positions)
  return positions_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
doc_info::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_list:posting_message.doc_info.positions)
  return &positions_;
}

// -------------------------------------------------------------------

// Posting

// int32 docID = 1;
inline void Posting::clear_docid() {
  docid_ = 0;
}
inline ::google::protobuf::int32 Posting::docid() const {
  // @@protoc_insertion_point(field_get:posting_message.Posting.docID)
  return docid_;
}
inline void Posting::set_docid(::google::protobuf::int32 value) {
  
  docid_ = value;
  // @@protoc_insertion_point(field_set:posting_message.Posting.docID)
}

// int32 term_frequency = 2;
inline void Posting::clear_term_frequency() {
  term_frequency_ = 0;
}
inline ::google::protobuf::int32 Posting::term_frequency() const {
  // @@protoc_insertion_point(field_get:posting_message.Posting.term_frequency)
  return term_frequency_;
}
inline void Posting::set_term_frequency(::google::protobuf::int32 value) {
  
  term_frequency_ = value;
  // @@protoc_insertion_point(field_set:posting_message.Posting.term_frequency)
}

// repeated int32 positions = 3;
inline int Posting::positions_size() const {
  return positions_.size();
}
inline void Posting::clear_positions() {
  positions_.Clear();
}
inline ::google::protobuf::int32 Posting::positions(int index) const {
  // @@protoc_insertion_point(field_get:posting_message.Posting.positions)
  return positions_.Get(index);
}
inline void Posting::set_positions(int index, ::google::protobuf::int32 value) {
  positions_.Set(index, value);
  // @@protoc_insertion_point(field_set:posting_message.Posting.positions)
}
inline void Posting::add_positions(::google::protobuf::int32 value) {
  positions_.Add(value);
  // @@protoc_insertion_point(field_add:posting_message.Posting.positions)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Posting::positions() const {
  // @@protoc_insertion_point(field_list:posting_message.Posting.positions)
  return positions_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Posting::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_list:posting_message.Posting.positions)
  return &positions_;
}

// -------------------------------------------------------------------

// PostingList

// int32 num_postings = 1;
inline void PostingList::clear_num_postings() {
  num_postings_ = 0;
}
inline ::google::protobuf::int32 PostingList::num_postings() const {
  // @@protoc_insertion_point(field_get:posting_message.PostingList.num_postings)
  return num_postings_;
}
inline void PostingList::set_num_postings(::google::protobuf::int32 value) {
  
  num_postings_ = value;
  // @@protoc_insertion_point(field_set:posting_message.PostingList.num_postings)
}

// repeated .posting_message.Posting postings = 2;
inline int PostingList::postings_size() const {
  return postings_.size();
}
inline void PostingList::clear_postings() {
  postings_.Clear();
}
inline const ::posting_message::Posting& PostingList::postings(int index) const {
  // @@protoc_insertion_point(field_get:posting_message.PostingList.postings)
  return postings_.Get(index);
}
inline ::posting_message::Posting* PostingList::mutable_postings(int index) {
  // @@protoc_insertion_point(field_mutable:posting_message.PostingList.postings)
  return postings_.Mutable(index);
}
inline ::posting_message::Posting* PostingList::add_postings() {
  // @@protoc_insertion_point(field_add:posting_message.PostingList.postings)
  return postings_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::posting_message::Posting >*
PostingList::mutable_postings() {
  // @@protoc_insertion_point(field_mutable_list:posting_message.PostingList.postings)
  return &postings_;
}
inline const ::google::protobuf::RepeatedPtrField< ::posting_message::Posting >&
PostingList::postings() const {
  // @@protoc_insertion_point(field_list:posting_message.PostingList.postings)
  return postings_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace posting_message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_posting_5fmessage_2eproto__INCLUDED
