// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: posting_message.proto

#include "posting_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace posting_message {
class doc_infoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<doc_info>
      _instance;
} _doc_info_default_instance_;
class PostingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Posting>
      _instance;
} _Posting_default_instance_;
class PostingListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PostingList>
      _instance;
} _PostingList_default_instance_;
}  // namespace posting_message
namespace protobuf_posting_5fmessage_2eproto {
void InitDefaultsdoc_infoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::posting_message::_doc_info_default_instance_;
    new (ptr) ::posting_message::doc_info();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::posting_message::doc_info::InitAsDefaultInstance();
}

void InitDefaultsdoc_info() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsdoc_infoImpl);
}

void InitDefaultsPostingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::posting_message::_Posting_default_instance_;
    new (ptr) ::posting_message::Posting();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::posting_message::Posting::InitAsDefaultInstance();
}

void InitDefaultsPosting() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPostingImpl);
}

void InitDefaultsPostingListImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_posting_5fmessage_2eproto::InitDefaultsPosting();
  {
    void* ptr = &::posting_message::_PostingList_default_instance_;
    new (ptr) ::posting_message::PostingList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::posting_message::PostingList::InitAsDefaultInstance();
}

void InitDefaultsPostingList() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPostingListImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::doc_info, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::doc_info, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::doc_info, term_frequency_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::doc_info, positions_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::Posting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::Posting, docid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::Posting, term_frequency_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::Posting, positions_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::PostingList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::PostingList, num_postings_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::posting_message::PostingList, postings_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::posting_message::doc_info)},
  { 8, -1, sizeof(::posting_message::Posting)},
  { 16, -1, sizeof(::posting_message::PostingList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::posting_message::_doc_info_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::posting_message::_Posting_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::posting_message::_PostingList_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "posting_message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025posting_message.proto\022\017posting_message"
      "\"A\n\010doc_info\022\n\n\002id\030\001 \001(\005\022\026\n\016term_frequen"
      "cy\030\002 \001(\005\022\021\n\tpositions\030\003 \003(\005\"C\n\007Posting\022\r"
      "\n\005docID\030\001 \001(\005\022\026\n\016term_frequency\030\002 \001(\005\022\021\n"
      "\tpositions\030\003 \003(\005\"O\n\013PostingList\022\024\n\014num_p"
      "ostings\030\001 \001(\005\022*\n\010postings\030\002 \003(\0132\030.postin"
      "g_message.Postingb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 265);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "posting_message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_posting_5fmessage_2eproto
namespace posting_message {

// ===================================================================

void doc_info::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int doc_info::kIdFieldNumber;
const int doc_info::kTermFrequencyFieldNumber;
const int doc_info::kPositionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

doc_info::doc_info()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_posting_5fmessage_2eproto::InitDefaultsdoc_info();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:posting_message.doc_info)
}
doc_info::doc_info(const doc_info& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      positions_(from.positions_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&term_frequency_) -
    reinterpret_cast<char*>(&id_)) + sizeof(term_frequency_));
  // @@protoc_insertion_point(copy_constructor:posting_message.doc_info)
}

void doc_info::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&term_frequency_) -
      reinterpret_cast<char*>(&id_)) + sizeof(term_frequency_));
  _cached_size_ = 0;
}

doc_info::~doc_info() {
  // @@protoc_insertion_point(destructor:posting_message.doc_info)
  SharedDtor();
}

void doc_info::SharedDtor() {
}

void doc_info::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* doc_info::descriptor() {
  ::protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const doc_info& doc_info::default_instance() {
  ::protobuf_posting_5fmessage_2eproto::InitDefaultsdoc_info();
  return *internal_default_instance();
}

doc_info* doc_info::New(::google::protobuf::Arena* arena) const {
  doc_info* n = new doc_info;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void doc_info::Clear() {
// @@protoc_insertion_point(message_clear_start:posting_message.doc_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  positions_.Clear();
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&term_frequency_) -
      reinterpret_cast<char*>(&id_)) + sizeof(term_frequency_));
  _internal_metadata_.Clear();
}

bool doc_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:posting_message.doc_info)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 term_frequency = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &term_frequency_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 positions = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_positions())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_positions())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:posting_message.doc_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:posting_message.doc_info)
  return false;
#undef DO_
}

void doc_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:posting_message.doc_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->term_frequency(), output);
  }

  // repeated int32 positions = 3;
  if (this->positions_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _positions_cached_byte_size_));
  }
  for (int i = 0, n = this->positions_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->positions(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:posting_message.doc_info)
}

::google::protobuf::uint8* doc_info::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:posting_message.doc_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->term_frequency(), target);
  }

  // repeated int32 positions = 3;
  if (this->positions_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _positions_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->positions_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:posting_message.doc_info)
  return target;
}

size_t doc_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:posting_message.doc_info)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 positions = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->positions_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _positions_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->term_frequency());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void doc_info::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:posting_message.doc_info)
  GOOGLE_DCHECK_NE(&from, this);
  const doc_info* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const doc_info>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:posting_message.doc_info)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:posting_message.doc_info)
    MergeFrom(*source);
  }
}

void doc_info::MergeFrom(const doc_info& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:posting_message.doc_info)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  positions_.MergeFrom(from.positions_);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.term_frequency() != 0) {
    set_term_frequency(from.term_frequency());
  }
}

void doc_info::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:posting_message.doc_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void doc_info::CopyFrom(const doc_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:posting_message.doc_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool doc_info::IsInitialized() const {
  return true;
}

void doc_info::Swap(doc_info* other) {
  if (other == this) return;
  InternalSwap(other);
}
void doc_info::InternalSwap(doc_info* other) {
  using std::swap;
  positions_.InternalSwap(&other->positions_);
  swap(id_, other->id_);
  swap(term_frequency_, other->term_frequency_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata doc_info::GetMetadata() const {
  protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Posting::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Posting::kDocIDFieldNumber;
const int Posting::kTermFrequencyFieldNumber;
const int Posting::kPositionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Posting::Posting()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_posting_5fmessage_2eproto::InitDefaultsPosting();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:posting_message.Posting)
}
Posting::Posting(const Posting& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      positions_(from.positions_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&docid_, &from.docid_,
    static_cast<size_t>(reinterpret_cast<char*>(&term_frequency_) -
    reinterpret_cast<char*>(&docid_)) + sizeof(term_frequency_));
  // @@protoc_insertion_point(copy_constructor:posting_message.Posting)
}

void Posting::SharedCtor() {
  ::memset(&docid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&term_frequency_) -
      reinterpret_cast<char*>(&docid_)) + sizeof(term_frequency_));
  _cached_size_ = 0;
}

Posting::~Posting() {
  // @@protoc_insertion_point(destructor:posting_message.Posting)
  SharedDtor();
}

void Posting::SharedDtor() {
}

void Posting::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Posting::descriptor() {
  ::protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Posting& Posting::default_instance() {
  ::protobuf_posting_5fmessage_2eproto::InitDefaultsPosting();
  return *internal_default_instance();
}

Posting* Posting::New(::google::protobuf::Arena* arena) const {
  Posting* n = new Posting;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Posting::Clear() {
// @@protoc_insertion_point(message_clear_start:posting_message.Posting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  positions_.Clear();
  ::memset(&docid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&term_frequency_) -
      reinterpret_cast<char*>(&docid_)) + sizeof(term_frequency_));
  _internal_metadata_.Clear();
}

bool Posting::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:posting_message.Posting)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 docID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &docid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 term_frequency = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &term_frequency_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 positions = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_positions())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_positions())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:posting_message.Posting)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:posting_message.Posting)
  return false;
#undef DO_
}

void Posting::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:posting_message.Posting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 docID = 1;
  if (this->docid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->docid(), output);
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->term_frequency(), output);
  }

  // repeated int32 positions = 3;
  if (this->positions_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _positions_cached_byte_size_));
  }
  for (int i = 0, n = this->positions_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->positions(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:posting_message.Posting)
}

::google::protobuf::uint8* Posting::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:posting_message.Posting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 docID = 1;
  if (this->docid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->docid(), target);
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->term_frequency(), target);
  }

  // repeated int32 positions = 3;
  if (this->positions_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _positions_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->positions_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:posting_message.Posting)
  return target;
}

size_t Posting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:posting_message.Posting)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 positions = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->positions_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _positions_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // int32 docID = 1;
  if (this->docid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->docid());
  }

  // int32 term_frequency = 2;
  if (this->term_frequency() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->term_frequency());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Posting::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:posting_message.Posting)
  GOOGLE_DCHECK_NE(&from, this);
  const Posting* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Posting>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:posting_message.Posting)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:posting_message.Posting)
    MergeFrom(*source);
  }
}

void Posting::MergeFrom(const Posting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:posting_message.Posting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  positions_.MergeFrom(from.positions_);
  if (from.docid() != 0) {
    set_docid(from.docid());
  }
  if (from.term_frequency() != 0) {
    set_term_frequency(from.term_frequency());
  }
}

void Posting::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:posting_message.Posting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Posting::CopyFrom(const Posting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:posting_message.Posting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Posting::IsInitialized() const {
  return true;
}

void Posting::Swap(Posting* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Posting::InternalSwap(Posting* other) {
  using std::swap;
  positions_.InternalSwap(&other->positions_);
  swap(docid_, other->docid_);
  swap(term_frequency_, other->term_frequency_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Posting::GetMetadata() const {
  protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PostingList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PostingList::kNumPostingsFieldNumber;
const int PostingList::kPostingsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PostingList::PostingList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_posting_5fmessage_2eproto::InitDefaultsPostingList();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:posting_message.PostingList)
}
PostingList::PostingList(const PostingList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      postings_(from.postings_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  num_postings_ = from.num_postings_;
  // @@protoc_insertion_point(copy_constructor:posting_message.PostingList)
}

void PostingList::SharedCtor() {
  num_postings_ = 0;
  _cached_size_ = 0;
}

PostingList::~PostingList() {
  // @@protoc_insertion_point(destructor:posting_message.PostingList)
  SharedDtor();
}

void PostingList::SharedDtor() {
}

void PostingList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PostingList::descriptor() {
  ::protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PostingList& PostingList::default_instance() {
  ::protobuf_posting_5fmessage_2eproto::InitDefaultsPostingList();
  return *internal_default_instance();
}

PostingList* PostingList::New(::google::protobuf::Arena* arena) const {
  PostingList* n = new PostingList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PostingList::Clear() {
// @@protoc_insertion_point(message_clear_start:posting_message.PostingList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  postings_.Clear();
  num_postings_ = 0;
  _internal_metadata_.Clear();
}

bool PostingList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:posting_message.PostingList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num_postings = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_postings_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .posting_message.Posting postings = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_postings()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:posting_message.PostingList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:posting_message.PostingList)
  return false;
#undef DO_
}

void PostingList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:posting_message.PostingList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_postings = 1;
  if (this->num_postings() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_postings(), output);
  }

  // repeated .posting_message.Posting postings = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->postings_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->postings(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:posting_message.PostingList)
}

::google::protobuf::uint8* PostingList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:posting_message.PostingList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_postings = 1;
  if (this->num_postings() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_postings(), target);
  }

  // repeated .posting_message.Posting postings = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->postings_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->postings(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:posting_message.PostingList)
  return target;
}

size_t PostingList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:posting_message.PostingList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .posting_message.Posting postings = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->postings_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->postings(static_cast<int>(i)));
    }
  }

  // int32 num_postings = 1;
  if (this->num_postings() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_postings());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PostingList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:posting_message.PostingList)
  GOOGLE_DCHECK_NE(&from, this);
  const PostingList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PostingList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:posting_message.PostingList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:posting_message.PostingList)
    MergeFrom(*source);
  }
}

void PostingList::MergeFrom(const PostingList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:posting_message.PostingList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  postings_.MergeFrom(from.postings_);
  if (from.num_postings() != 0) {
    set_num_postings(from.num_postings());
  }
}

void PostingList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:posting_message.PostingList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PostingList::CopyFrom(const PostingList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:posting_message.PostingList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PostingList::IsInitialized() const {
  return true;
}

void PostingList::Swap(PostingList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PostingList::InternalSwap(PostingList* other) {
  using std::swap;
  postings_.InternalSwap(&other->postings_);
  swap(num_postings_, other->num_postings_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PostingList::GetMetadata() const {
  protobuf_posting_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_posting_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace posting_message

// @@protoc_insertion_point(global_scope)
